server:
  port: 8083

spring:
  application:
    name: market-data-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5438/marketdatadb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: market-data-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    db:
      enabled: false
    diskspace:
      enabled: true
    ping:
      enabled: true

app:
  kafka:
    enabled: ${APP_KAFKA_ENABLED:true}