spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: trading-orders
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**

        - id: trading-admin
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/**

        - id: trading-my-trades
          uri: http://localhost:8082
          predicates:
            - Path=/api/trades/mine

        - id: market-orderbook
          uri: http://localhost:8083
          predicates:
            - Path=/api/orderbook/**

        - id: market-trades
          uri: http://localhost:8083
          predicates:
            - Path=/api/trades/**
eureka:
  client:
    enabled: false